server:
  port: 8081

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: library-events-listener-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "com.learnkafka.model"
        spring.json.value.default.type: "com.learnkafka.model.LibraryEventDto"
        spring.json.use.type.headers: false
