server:
  port: ${SERVER_PORT:8081}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:library-events-listener-group}
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "com.learnkafka.model"
        spring.json.value.default.type: "com.learnkafka.model.LibraryEventDto"
        spring.json.use.type.headers: false
