spring:
  application:
    name: library-events-producer-v2
  profiles:
    active: dev
  kafka:
    topic:
      name: library-events
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
